### ISSUE TITLE
Creating a C function for callback

### ISSUE THREAD

**Issue by LoganDark** [ffi-cross/js-ffi-cross#3]
Hey, I need some way to create a C function that calls into my JS code, and obtain a pointer to that function so I can give it to a DLL. That way the DLL can call my function directly on interesting events instead of me having to poll. Is there any way you could add this functionality to ffi-cross?

**Comment by lygstate** [comment]
https://github.com/ffi-cross/js-ffi-cross/blob/d380b14c178ae00e34c6cbaa45a83e95274d401c/test/typescript/ffi-napi-tests.ts#L46

**Comment by LoganDark** [comment]
Ty, upon further looking it seems this is gone over in the tutorial - so sorry!! At least now if someone misses it, there's an issue pointing them in the right direction ([Here](https://github.com/ffi-cross/js-ffi-cross/blob/57162e69f8869fd0b347f261b52985ead79669cf/docs/tutorial.md#callbacks))
