### ISSUE TITLE
ref.types is not in the TypeScript type declarations

### ISSUE THREAD

**Issue by LoganDark** [ffi-cross/js-ffi-cross#5]
![image](https://user-images.githubusercontent.com/4723091/129988595-e325d536-3332-47da-8476-efbb1fc4c633.png)

**Comment by lygstate** [comment]
import { types } from ''ffi-cross' instead

**Comment by LoganDark** [comment]
> import { types } from ''ffi-cross' instead

Your tutorial is out of date then :) Thanks!
